package com.chinaitop.depot.system.mapper;

import com.chinaitop.depot.system.model.UserOperationtype;
import com.chinaitop.depot.system.model.UserOperationtypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserOperationtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operationtype
     *
     * @mbggenerated Wed Nov 28 14:18:51 CST 2018
     */
    int countByExample(UserOperationtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operationtype
     *
     * @mbggenerated Wed Nov 28 14:18:51 CST 2018
     */
    int deleteByExample(UserOperationtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operationtype
     *
     * @mbggenerated Wed Nov 28 14:18:51 CST 2018
     */
    int deleteByPrimaryKey(Integer uotId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operationtype
     *
     * @mbggenerated Wed Nov 28 14:18:51 CST 2018
     */
    int insert(UserOperationtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operationtype
     *
     * @mbggenerated Wed Nov 28 14:18:51 CST 2018
     */
    int insertSelective(UserOperationtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operationtype
     *
     * @mbggenerated Wed Nov 28 14:18:51 CST 2018
     */
    List<UserOperationtype> selectByExample(UserOperationtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operationtype
     *
     * @mbggenerated Wed Nov 28 14:18:51 CST 2018
     */
    UserOperationtype selectByPrimaryKey(Integer uotId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operationtype
     *
     * @mbggenerated Wed Nov 28 14:18:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserOperationtype record, @Param("example") UserOperationtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operationtype
     *
     * @mbggenerated Wed Nov 28 14:18:51 CST 2018
     */
    int updateByExample(@Param("record") UserOperationtype record, @Param("example") UserOperationtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operationtype
     *
     * @mbggenerated Wed Nov 28 14:18:51 CST 2018
     */
    int updateByPrimaryKeySelective(UserOperationtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operationtype
     *
     * @mbggenerated Wed Nov 28 14:18:51 CST 2018
     */
    int updateByPrimaryKey(UserOperationtype record);
}