package com.chinaitop.depot.system.mapper;

import com.chinaitop.depot.system.model.UserOperationlog;
import com.chinaitop.depot.system.model.UserOperationlogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserOperationlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operationlog
     *
     * @mbggenerated Wed Nov 28 14:24:18 CST 2018
     */
    int countByExample(UserOperationlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operationlog
     *
     * @mbggenerated Wed Nov 28 14:24:18 CST 2018
     */
    int deleteByExample(UserOperationlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operationlog
     *
     * @mbggenerated Wed Nov 28 14:24:18 CST 2018
     */
    int deleteByPrimaryKey(Integer uolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operationlog
     *
     * @mbggenerated Wed Nov 28 14:24:18 CST 2018
     */
    int insert(UserOperationlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operationlog
     *
     * @mbggenerated Wed Nov 28 14:24:18 CST 2018
     */
    int insertSelective(UserOperationlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operationlog
     *
     * @mbggenerated Wed Nov 28 14:24:18 CST 2018
     */
    List<UserOperationlog> selectByExample(UserOperationlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operationlog
     *
     * @mbggenerated Wed Nov 28 14:24:18 CST 2018
     */
    UserOperationlog selectByPrimaryKey(Integer uolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operationlog
     *
     * @mbggenerated Wed Nov 28 14:24:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserOperationlog record, @Param("example") UserOperationlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operationlog
     *
     * @mbggenerated Wed Nov 28 14:24:18 CST 2018
     */
    int updateByExample(@Param("record") UserOperationlog record, @Param("example") UserOperationlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operationlog
     *
     * @mbggenerated Wed Nov 28 14:24:18 CST 2018
     */
    int updateByPrimaryKeySelective(UserOperationlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operationlog
     *
     * @mbggenerated Wed Nov 28 14:24:18 CST 2018
     */
    int updateByPrimaryKey(UserOperationlog record);
}